package com.dao.convention.services

private const val CSV_HEADER =
    "GROUP,PACKAGE,CLASS,INSTRUCTION_MISSED,INSTRUCTION_COVERED,BRANCH_MISSED,BRANCH_COVERED,LINE_MISSED,LINE_COVERED,COMPLEXITY_MISSED,COMPLEXITY_COVERED,METHOD_MISSED,METHOD_COVERED"

private const val CSV_ROW =
    "my-group,my-package,MyClass,0,10,0,2,0,5,0,1,0,1"

internal const val CSV_CONTENT = "$CSV_HEADER\n$CSV_ROW\n"
