[versions]
agp = "9.4.1"
kotlin = "2.4.20"
jvm-target = "26"
detekt = "2.0.0-alpha.6"
hilt = "2.60.1"
jacoco = "0.8.15"
ksp = "2.3.12"
ktlint = "1.8.0"
spotless = "8.10.2"

android-appcompat = "1.8.0"
android-core = "1.19.0"
android-gradle-lint = "1.0.0"
android-lifecycle = "2.11.0"
android-material = "1.14.0"

compose-bom = "2026.09.00"
compose-activity = "1.13.0"
compose-rules = "0.6.6"
compose-slack-lint = "1.6.0"
compose-twitter-rules = "0.0.26"

test-android = "1.7.0"
test-android-junit = "1.3.0"
test-espresso = "3.7.0"
test-junit = "4.13.2"
test-robolectric = "4.17"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-base = { id = "com.android.base", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-lint = { id = "com.android.lint", version.ref = "agp" }
convention-android-application = { id = "convention.android.application" }
convention-android-compose = { id = "convention.android.compose" }
convention-android-feature = { id = "convention.android.feature" }
convention-android-library = { id = "convention.android.library" }
convention-hilt = { id = "convention.hilt" }
convention-kotlin-jvm = { id = "convention.kotlin.jvm" }
convention-root = { id = "convention.root" }
detekt = { id = "dev.detekt", version.ref = "detekt" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[libraries]
android-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "android-appcompat" }
android-core = { group = "androidx.core", name = "core-ktx", version.ref = "android-core" }
android-gradle-lint = { group = "androidx.lint", name = "lint-gradle", version.ref = "android-gradle-lint" }
android-material = { group = "com.google.android.material", name = "material", version.ref = "android-material" }

compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "compose-activity" }
compose-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "android-lifecycle" }
compose-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "android-lifecycle" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
detekt-compose-rules = { group = "io.nlopez.compose.rules", name = "detekt", version.ref = "compose-rules" }
detekt-twitter-compose-rules = { group = "com.twitter.compose.rules", name = "detekt", version.ref = "compose-twitter-rules" }
ktlint-compose-rules = { group = "io.nlopez.compose.rules", name = "ktlint", version.ref = "compose-rules" }
slack-lint-compose = { group = "com.slack.lint.compose", name = "compose-lint-checks", version.ref = "compose-slack-lint" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-core = { group = "com.google.dagger", name = "hilt-core", version.ref = "hilt" }

test-android-core = { module = "androidx.test:core", version.ref = "test-android" }
test-android-junit = { group = "androidx.test.ext", name = "junit", version.ref = "test-android-junit" }
test-android-rules = { module = "androidx.test:rules", version.ref = "test-android" }
test-android-runner = { module = "androidx.test:runner", version.ref = "test-android" }
test-compose-ui-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
test-compose-ui-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "test-espresso" }
test-junit = { group = "junit", name = "junit", version.ref = "test-junit" }
test-kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
test-robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "test-robolectric" }

android-gradle-plugin = { group = "com.android.tools.build", name = "gradle-api", version.ref = "agp" }
detekt-gradle-plugin = { group = "dev.detekt", name = "detekt-gradle-plugin", version.ref = "detekt" }
spotless-gradle-plugin = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }

[bundles]
compose-ui-tooling = [
    "compose-ui-tooling",
    "test-compose-ui-manifest"
]
